# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Music Works
  version: 1
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Philosophy
      url: /progressive_approach.html
      output: web

    - title: Melodic Shape
      url: /melodic_shape.html
      output: web, pdf

    - title: Building a Singable, Memorable Melody
      url: /bsm.html
      output: web, pdf 

    - title: aQWERTYon and Noteflight
      url: /aqwertyon_with_noteflight.html
      output: web, pdf  

    - title: Musical Alphabet
      url: /musical_alphabet.html
      output: web, pdf   

    - title: Sense of Key
      url: /sense_of_key.html
      output: web, pdf

    - title: Using the Staff
      url: /using_the_staff.html
      output: web, pdf

    - title: Begin Your Composition
      url: /begin_your_composition.html
      output: web, pdf  

    - title: Developing a Melody
      url: /developing_a_melody.html
      output: web, pdf

    - title: Form
      url: /form.html
      output: web, pdf  

  - title: Harmony
    output: web, pdf

    folderitems:
    - title: Putting Notes Together
      url: /putting_notes_together.html
      output: web, pdf

    - title: Resolution
      url: /resolution.html
      output: web, pdf

    - title: Add 2nd Instrument
      url: /add_2nd_instrument.html
      output: web, pdf

    - title: Add 3rd Instrument
      url: /add_3rd_instrument.html
      output: web, pdf

    - title: Intervals That Are 2 Skips 
      url: /leaps.html
      output: web, pdf
