# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Music Works
  version: 2
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:

    - title: Technical Requirements
      url: /technical_info.html
      output: web  

    - title: Overview
      url: /mw2home.html
      output: web

  - title: Chords
    output: web, pdf
    folderitems: 
    
    - title: 3 Note Chords
      url: /3_note_chords.html
      output: web  

    - title: Play 3 Note Chords
      url: /play_3_note_chords.html
      output: web    

  
