# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Music Works
  version: 2
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:

    - title: Technical Requirements
      url: /technical_info.html
      output: web  

    - title: Overview
      url: /mw2home.html
      output: web

  - title: Chords
    output: web, pdf
    folderitems: 
    
    - title: 3 Note Chords
      url: /3_note_chords.html
      output: web  

    - title: Play 3 Note Chords
      url: /play_3_note_chords.html
      output: web 

    - title: aQWERTYon and Noteflight
      url: /aqwertyon_and_noteflight.html
      output: web 

    - title: Build 3 Note Chords
      url: /build_3_note_chords.html
      output: web  

    - title: Diatonic Chords
      url: /diatonic_chords.html
      output: web   

    - title: Chord Progressions
      url: /chord_progressions.html
      output: web  

    - title: Play A Minor and D Minor
      url: /play_a_minor_d_minor.html
      output: web 

    - title: Let It Be
      url: /let_it_be.html
      output: web 

    - title: Begin Composition 2
      url: /begin_composition_2.html
      output: web

  - title: Melody and Chords
    output: web, pdf
    folderitems:
    
    - title: Melody and Chords
      url: /melody_and_chords.html
      output: web 

    - title: Notating a Melody
      url: /notating_a_melody.html
      output: web 

    - title: Melody and Chords Noteflight 1
      url: /melody_and_chords_1.html
      output: web
      
    - title: Melody and Chords Noteflight 2
      url: /melody_and_chords_2.html
      output: web
      
    - title: Add a Melody to Your Chord Progression
      url: /add_a_melody_to_your_chord_progression.html
      output: web
      
    - title: Orchestrating a Chord Progression
      url: /orchestrating_a_chord_progression.html
      output: web
      
    - title: Orchestrate This Chord Progression
      url: /orchestrate_this_chord_progression.html
      output: web                       





  
